#!/bin/sh
# this program is called by dunst whenever a notification is sent.
# https://wiki.archlinux.org/title/Dunst#Scripting
# appname <$1> summary <$2> body <$3> icon <$4> urgency <$5>
# it will parse the notification and snatch 2fa codes using a regex

[ "$2" = " TOTP Notification Watcher" ] && exit

# the actual regex needs work. pls help
totp="$(echo $3 | grep -E -o "(^|[a-zA-Z]| )+[0-9]{6}([a-zA-Z]| |$)+")"

[ -z $totp ] && exit

## save contents of clipboard
#oldclip="$(xclip -out -selection clipboard)"
# copy totp to clipboard
echo $totp | xclip -selection clipboard
notify-send " TOTP Notification Watcher" "$totp copied to clipboard"

## restore clipboard contents
#echo $oldclip | xclip -selection clipboard
#notify-send " TOTP Notification Watcher" "Clipboard contents restored"

sleep 10s
# clear clipboard
printf "" | xclip -selection clipboard
