#!/bin/sh

#while getopts "hc" o; do case "${o}" in
#	c) extracthere="True" ;;
#	*) printf "Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit ;;
#esac done

#exInFolder() { \
#	archive="$(readlink -f "$*")" &&
#	directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
#	mkdir -p "$directory" &&
#	cd "$directory" || exit
#}
archive="$1"

exInFolder() { \
	directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
	mkdir -p "$directory" &&
	cd "$directory" &&
	archive="../$(echo $archive | awk -F'/' '{print $NF}')"
}

#archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)")"

[ "$archive" = "" ] && printf "Give archive to extract as argument.\\n" && exit

if [ -f "$archive" ] ; then
	case "$archive" in
		*.tar.bz2|*.tbz2) tar xjfv "$archive" ;;
		*.tar.xz) tar xfv "$archive" ;;
		*.tar.gz|*.tgz) tar xzfv "$archive" ;;
		*.tar.zst|*.tzst) tar -I zstd -xf "$archive" ;;
		*.jar) exInFolder && jar xfv "$archive" ;;
		*.lzma) unlzma "$archive" ;;
		*.lz4) unlz4 "$archive" ;;
		*.bz2) bunzip2 "$archive" ;;
		*.rar) exInFolder && unrar x -ad "$archive" ;;
		*.gz) gunzip "$archive" ;;
		*.tar) exInFolder && tar xfv "$archive" ;;
		*.zip) exInFolder && unzip "$archive" ;;
		*.Z) uncompress "$archive" ;;
		*.7z) 7z x "$archive" ;;
		*.xz) unxz "$archive" ;;
		*.exe) exInFolder && cabextract "$archive" ;;
		*.deb) exInFolder && ar -x "$archive" ;;
		*) printf "extract: '%s' - unknown archive method\\n" "$archive" ;;
	esac
else
	printf "File \"%s\" not found.\\n" "$archive"
fi
