#!/bin/sh
# This is a CLI frontend for cryptsetup
# Setup must be manual

[ "$1" = "" ] && exit

calcmounts() {
	[ "$(ls /mnt/secret | wc -l)" = 0 ] && echo "container0" && return

	lastdir="$(ls /mnt/secret | tail -n1 | tr -d 'a-zA-Z')"
	newdir=$((lastdir + 1))
	echo "container$newdir"
}

if [ -f "$1.inf" ]; then
	loopback="$(awk -F';' '{print $1}' $1.inf)"
	mntname="$(awk -F';' '{print $2}' $1.inf)"
	doas umount /mnt/secret/"$mntname"
	doas cryptsetup close "$mntname"
	doas losetup --detach "$loopback"
	[ "$(ls /mnt/secret/"$mntname" | wc -l)" != 0 ] && notify-send " Files are still present in /mnt/secret/$mntname" "Will not remove. Please check folder" && exit
	doas rm -r /mnt/secret/"$mntname"
	rm "$1.inf"
	notify-send "✅ Successfully unmounted"
else
	loopback="$(doas losetup --find)"
	mntname="$(calcmounts)"
	echo "$loopback;$mntname" > "$1.inf"

	doas mkdir /mnt/secret/"$mntname"
	doas losetup "$loopback" "$1"
	doas cryptsetup open "$loopback" "$mntname"
	# stupid fix to get ext4 and fat fs working
	doas mount /dev/mapper/"$mntname" /mnt/secret/"$mntname" -o uid="$(whoami)",gid="$(whoami)" || doas mount /dev/mapper/"$mntname" /mnt/secret/"$mntname"
	notify-send "✅ Successfully mounted"
fi
