#!/bin/sh

# requires htmlq

mkdir -p "$XDG_CACHE_HOME"/moth

# Simple script to download today's math pdf file from CorbettMaths
# Stores pdf in a temporary file in $XDG_CACHE_HOME/moth

# Type (either "gcse" "primary" "further-maths" "gcse1" "core1")
# ALSO: "primary" uses a different website. Script may require further editing
type=$(echo "core1\\ngcse\\ngcse1\\nfurther-maths" | dmenu -p "Pick a type")

# Difficulty
# if "gcse": either "Numeracy" "Foundation" "Foundation Plus" "Higher" "Higher Plus"
# if "further-maths": "Further Maths"
# if "gcse1": either "Numeracy" "Foundation" "Higher"
# if "core": either "Core1"
if [ $type = "core" ]; then
	difficulty="Core 1"
elif [ $type = "gcse" ]; then
	difficulty=$(echo "Numeracy\\nFoundation\\nFoundation Plus\\nHigher\\nHigher Plus" | dmenu -p "Pick a difficulty")
elif [ $type = "gcse1" ]; then
	difficulty=$(echo "Numeracy\\nFoundation\\nHigher" | dmenu -p "Pick a difficulty")
elif [ $type = "further-maths" ]; then
	difficulty="Further Maths"
fi

url="$(curl -s "https://corbettmaths.com/5-a-day/$type/" | grep -iE "$(date +%d | sed -E 's/^0//g').{3}$(date +%B)" | htmlq -a "href" "*" | grep -i "$difficulty" | head -n1)"

# answers for core1 will NOT work as they do not exist
# also gcse1 since it unites answers for all tiers into one pdf
if [ "$type" = "further-maths" ]; then
	answerurl="$(curl -s "https://corbettmaths.com/5-a-day/further-maths/" | grep -iE "$(date +%d | sed -E 's/^0//g').{3}$(date +%B)" | htmlq -a href "*" | grep -i "ans")"
else
	answerpage="$(curl -s "https://corbettmaths.com/5-a-day/$type/" | grep -i "$(date '+%B')-answers" | htmlq -a "href" "*" | head -n1)"
	answerurl="$(curl -s "$answerpage" | grep -iE "$(date +%d | sed -e 's/^0//g').{3}$(date +%b)" | htmlq -a href "*" | grep -i "$difficulty" | head -n1)"
fi


filename=$(</dev/urandom tr -dc 'A-Za-z0-9' | head -c 12)

wget "$url" -O "$XDG_CACHE_HOME"/moth/work.pdf >/dev/null 2>&1
wget "$answerurl" -O "$XDG_CACHE_HOME"/moth/answer.pdf >/dev/null 2>&1

pdfunite "$XDG_CACHE_HOME"/moth/work.pdf "$XDG_CACHE_HOME"/moth/answer.pdf "$XDG_CACHE_HOME"/moth/$filename.pdf || cp "$XDG_CACHE_HOME"/moth/work.pdf "$XDG_CACHE_HOME"/moth/$filename.pdf

rm "$XDG_CACHE_HOME"/moth/work.pdf
rm "$XDG_CACHE_HOME"/moth/answer.pdf

zathura "$XDG_CACHE_HOME"/moth/$filename.pdf

rm "$XDG_CACHE_HOME"/moth/$filename.pdf
