#!/bin/sh

# only select sources that are an actual microphone
sources="$(pamixer --list-sources | awk '!/Built/{ cnt++ ; if (cnt == 2) print $1 }')"

# check if the first source that is not a monitor is muted
muted="$(pamixer --source "$(echo "$sources" | head -1)" --get-mute)"

if [ "$muted" = "true" ]; then
	for i in $sources; do
		pamixer --source "$i" -u
	done
elif [ "$muted" = "false" ]; then
	for i in $sources; do
		pamixer --source "$i" -m
	done
else
	notify-send "muteinputs" "No inputs available"
fi
