#!/bin/sh

mkdir -p "$XDG_CACHE_HOME"/moth

# Simple script to download today's math pdf file from CorbettMaths
# Stores pdf in a temporary file in $XDG_CACHE_HOME/moth

# Type (either "gcse" "primary" "further-maths" "gcse1" "core1")
# ALSO: "primary" uses a different website. Script may require further editing
type=$(echo "core1\\ngcse\\ngcse1\\nfurther-maths" | dmenu -p "Pick a type")

# Difficulty
# if "gcse": either "Numeracy" "Foundation" "Foundation Plus" "Higher" "Higher Plus"
# if "further-maths": "Further Maths"
# if "gcse1": either "Numeracy" "Foundation" "Higher"
# if "core": either "Core1"
if [ $type = "core" ]; then
	difficulty="Core 1"
elif [ $type = "gcse" ]; then
	difficulty=$(echo "Numeracy\\nFoundation\\nFoundation Plus\\nHigher\\nHigher Plus" | dmenu -p "Pick a difficulty")
elif [ $type = "gcse1" ]; then
	difficulty=$(echo "Numeracy\\nFoundation\\nHigher" | dmenu -p "Pick a difficulty")
elif [ $type = "further-maths" ]; then
	difficulty="Further Maths"
fi

url="$(curl -s "https://corbettmaths.com/5-a-day/$type/" | sed 's/   /\n/g' | grep -E "$difficulty[^-P]" | sed 's/ /\n/g' | grep "href" | sed -e 's/href="// ; s/".*$//' | shuf | head -n1)"

filename=$(</dev/urandom tr -dc 'A-Za-z0-9' | head -c 12)

wget "$url" -O "$XDG_CACHE_HOME"/moth/$filename.pdf >/dev/null 2>&1

zathura "$XDG_CACHE_HOME"/moth/$filename.pdf

rm "$XDG_CACHE_HOME"/moth/$filename.pdf
